[package]
name = "openvnc-host"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[target.'cfg(windows)'.dependencies]
serde_json = "=1.0.145"
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging", "Win32_UI_Controls", "Win32_UI_Input_KeyboardAndMouse"] }
